# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: RSS Translator
site_url: https://rsstranslator.com
site_author: versun
site_description: >-
  Translate RSS feeds to your language

# Repository
repo_name: rss-translator/RSS-Translator
repo_url: https://github.com/rss-translator/RSS-Translator

# Copyright
copyright: Copyright &copy; 2023 - 2024 RSS Translator

theme:
  name: terminal # https://github.com/ntno/mkdocs-terminal
  palette: gruvbox_dark
  features:
    - footer.prev_next
    #- navigation.side.hide
    - navigation.side.indexes
    #- navigation.side.toc.hide
    - navigation.top.hide
    #- navigation.top.cursor_animation.hide
    #- navigation.top.search_button.hide
    - revision.date
    - revision.history
    #- style.links.underline.hide
  favicon: assets/logo.ico
  logo: assets/logo.ico

markdown_extensions:
  # Python Markdown
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - meta
  - toc:
      permalink: "#"
      permalink_title: Anchor link to this section for reference

  # PyMdown Extensions
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.snippets:
      base_path:
        - docs

plugins:
  - md-to-html
  - git-revision-date
  - macros
  - search
  - i18n:
        docs_structure: folder
        languages:
          - locale: zh
            default: true
            name: 中文
            build: true
          - locale: en
            name: English
            build: true
            nav_translations:
              主页: Home
              截图: Screenshots
              安装: Install
              脚本自动安装: Installation Script
              一键部署: One Click
              Docker安装: Docker
              升级: Upgrade
              开启SSL: Enable SSL
              使用说明: Guide
              翻译服务: Translate Services
              常见问题: FAQ
              开发进度: Roadmap
              赞助: Sponsorship



# Additional configuration
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/rss-translator/RSS-Translator
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/rsstranslator/rsstranslator
    - icon: fontawesome/brands/telegram
      link: https://t.me/rsstranslator
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/VersunPan

# Page tree
nav:
  - 主页: index.md
  - 截图: screenshots.md
  - Demo: demo.md
  - 安装:
      - Docker安装: install/docker.md
      - 一键部署: install/one-click.md
      - 脚本自动安装: install/install-script.md
  - 升级: upgrade.md
  - 开启SSL: ssl.md
  - 使用说明: guide.md
  - 翻译服务: translator.md
  - 常见问题: faq.md
  - 开发进度: https://github.com/orgs/rss-translator/projects/2/views/1
  - 赞助: https://rsstranslator.com/#_2
  - Github: https://github.com/rss-translator/RSS-Translator
  - Telegram: https://t.me/rsstranslator
  - Releases: https://github.com/rss-translator/RSS-Translator/releases
